#This configuration file will hold common configs to be shared among all files
spring:
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
  main:
    allow-bean-definition-overriding: true
#  cloud:
#    sentinel:
#      eager: true
#      transport:
#        dashboard: localhost:8099

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #where our registry server is located

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8081/auth/current
      token-info-uri: http://localhost:8081/auth/oauth/check_token
    client:
      clientId: mobile
      clientSecret: pecai98
      accessTokenUri: http://localhost:8081/auth/oauth/token
      grant-type: password
#      scope: health_mod

logging:
  level:
    org.springframework.security: DEBUG
