spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ams-assignment
    username: ams
    password: ams
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /assignment
  port: 8084

#server:
#  servlet:
#    context-path: /assignment
#  port: ${PORT:0}
#eureka:
#  instance:
#    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}
