spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course-db
    username: ams
    password: ams
    driver-class-name: org.postgresql.Driver
server:
  servlet:
    context-path: /course
  port: 8083
