spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student-db
    username: ams
    password: ams
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /student
  port: 8086
