package ro.ubbcluj.cs.ams.course.service.exception;

public enum CourseExceptionType {
    SUCCESS,
    DUPLICATE_COURSE,
    DUPLICATE_ASSIGN,
    INVALID_COURSE,
    INVALID_ASSIGN,
    USERNAME_NOT_FOUND,
    INVALID_USER_ROLE,
    ERROR,
    ASSIGNMENT_NOT_FOUND,
    COURSE_NOT_FOUND,
    SPECIALIZATION_NOT_FOUND,
    ACTIVITY_TYPE_NOT_FOUND,
    ENROLLMENT_NOT_FOUND,
    BAD_DATA
}
