spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared #tells spring where to locate the config files
#        git:
#          uri: https://github.com/katybucsa/config-server-files
#          username: katybucsa
#          password:
  profiles:
    active: native
  security:
    user:
      password: amsConfigServerPassword #the password which apps will use to access its configurations
  flyway:
    enabled: false #disable flyway for config server
  autoconfigure: #disable jpa repository for config server
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, \
      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, \
      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration


eureka: #not register with eureka
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8888
